version: "1"
name: highlight

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8082:8082"
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_EVENTS_STAGING_ENDPOINT=redis:6379
      - PSQL_HOST=postgres
      - CLICKHOUSE_ADDRESS=clickhouse:9000
    volumes:
      - highlight-data:/highlight-data
    depends_on:
      - postgres
      - redis
      - clickhouse
      - kafka

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000"
    environment:
      - REACT_APP_PUBLIC_GRAPH_URI=https://pub.highlight.io
      - REACT_APP_PRIVATE_GRAPH_URI=https://pri.highlight.io
      - REACT_APP_FRONTEND_URI=https://sentry.mariaperlman.com

  collector:
    build:
      context: .
      dockerfile: docker/collector.Dockerfile
    ports:
      - "4317"
      - "4318"
      - "4319"
      - "8318"
    environment:
      - SSL=true
      - IN_DOCKER_GO=true

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=highlight
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=highlight
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

volumes:
  highlight-data:
  postgres-data:
  redis-data:
  clickhouse-data: